Fixed build on i386 macOS with clang-11
Apparently, clang11 on i386 macOS uses `int` instead of `ssize_t` for
`a- b` where bot `a` and `b` is `char`. It leads to an error:
```
vtc_http.c:392:8: error: format specifies type 'ssize_t' (aka 'long') but the argument has type 'int' [-Werror,-Wformat]
                            p - hp->body, t, *p);
                            ^~~~~~~~~~~~
```